version: "2.4"
services:
  envoy:
    ipc: host
    image: envoyproxy/envoy:v1.26-latest
    restart: "always"
    networks:
      - nakama-net
    depends_on:
      nakama:
        condition: service_healthy
    expose:
      - "7348"
      - "7349"
      - "7350"
      - "7351"
      - "9901"
    ports:
      - "7348:7348"
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
      - "43594:9901"
    volumes:
      - ../conf/envoy/example.yml:/etc/envoy/envoy.yaml
      - ../conf/ssl/ca.pem:/etc/ssl/ca.pem
      - ../conf/ssl/cert.pem:/etc/ssl/cert.pem
      - ../conf/ssl/privkey.pem:/etc/ssl/privkey.pem

  cockroachdb:
    networks:
      - nakama-net
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "always"
    volumes:
      - ../data/crdb:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5

  etcd:
    networks:
      - nakama-net
    image: docker.io/bitnami/etcd:3.5.8-debian-11-r0
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/etcd/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_DATA_DIR=/bitnami/etcd/data
      - ETCDCTL_API=3
      - ETCD_ON_K8S=no
      - ETCD_START_FROM_SNAPSHOT=no
      - ETCD_DISASTER_RECOVERY=no
      - ETCD_AUTO_COMPACTION_MODE=periodic
      - ETCD_AUTO_COMPACTION_RETENTION=24
      - BITNAMI_DEBUG=false
    volumes:
      - ../data/etcd:/bitnami/etcd/data

  nakama:
    scale: 3
    build:
      context: ../pkgs/nakama-plus
      dockerfile: ./build/Dockerfile.local
    image: nakama
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        mkdir -p "/nakama/data/$$(dig -x $$(hostname -i) +short | cut -d . -f 1)/modules" &&
        exec /nakama/nakama --name "$$(dig -x $$(hostname -i) +short | cut -d . -f 1)" --data_dir "/nakama/data/$$(dig -x $$(hostname -i) +short | cut -d . -f 1)" --runtime.path "/nakama/data/$$(dig -x $$(hostname -i) +short | cut -d . -f 1)/modules" --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100 --config /nakama/config.yml
    restart: "always"
    links:
      - "cockroachdb:db"
    depends_on:
      etcd:
        condition: service_healthy
      cockroachdb:
        condition: service_healthy
      prometheus:
        condition: service_started
    volumes:
      - ../data/nakama:/nakama/data
      - ../conf/nakama/example.yml:/nakama/config.yml
      - ../conf/ssl/ca.pem:/nakama/ca.pem
      - ../conf/ssl/cert.pem:/nakama/cert.pem
      - ../conf/ssl/privkey.pem:/nakama/privkey.pem
    expose:
      - "7348"
      - "7349"
      - "7350"
      - "7351"
      - "7352"
      - "9100"
    networks:
      - nakama-net
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    networks:
      - nakama-net
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']

        - job_name: nakama
          metrics_path: /
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - "9090:9090"

volumes:
  data:

networks:
  nakama-net:
    name: nakama-net
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/25"
          gateway: "172.16.239.1"
